version: "3.1"
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo

  payment-provider-mock:
    image: composedemo.azurecr.io/payment-provider-mock:latest
    ports:
      - 8083:1080

  payment-history-populator:
    image: composedemo.azurecr.io/payments-history-populator:latest
    environment:
      - API_ENDPOINT=http://payment-provider-mock:1080/Payments
      - MONGO=mongodb://root:root@mongo:27017/
    depends_on:
      - mongo
      - payment-provider-mock

  payments-service:
    image: composedemo.azurecr.io/payments-service:latest
    environment:
      - MONGO=mongodb://root:root@mongo:27017/
    ports:
      - 8082:80
    depends_on:
      - mongo
